### ISSUE TITLE
API getTransactionInfoById

### ISSUE THREAD

**Issue by lamductan** [tronprotocol/wallet-cli#146]
How to use API getTransactionInfoById? I don't understand what parameters offset and limit mean. Could anyone give me an example to use this API?

**Comment by dinghu** [comment]
这个 接口会报错：
r: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: protocol.WalletExtension/GetTransactionsFromThis2
04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err:     at org.tron.api.WalletExtensionGrpc$WalletExtensionBlockingStub.getTransactionsFromThis2(WalletExtensionGrpc.java:352)
04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err:     at org.tron.walletserver.GrpcClient.getTransactionsFromThis(GrpcClient.java:224)

**Comment by sharkzhou** [comment]
> 这个 接口会报错：
> r: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: protocol.WalletExtension/GetTransactionsFromThis2
> 04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err: at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
> 04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err: at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
> 04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err: at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
> 04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err: at org.tron.api.WalletExtensionGrpc$WalletExtensionBlockingStub.getTransactionsFromThis2(WalletExtensionGrpc.java:352)
> 04-18 10:08:28.253 9385-11266/com.cph.topay W/System.err: at org.tron.walletserver.GrpcClient.getTransactionsFromThis(GrpcClient.java:224)

我也遇到了,请问有没有解决方案呀

**Comment by zk19862018** [comment]
GetTransactionsfromThis Address offset limit
