### ISSUE TITLE
ERROR [main] [Client](Client.java:2355) UNAVAILABLE: io exception when doin getbalance

### ISSUE THREAD

**Issue by BhumikaB** [tronprotocol/wallet-cli#278]
### getAddress
```
11:44:14.168 INFO  [main] [Client](Client.java:228) GetAddress successful !!
11:44:14.172 INFO  [main] [Client](Client.java:229) address = TNtqkBW9UWkSGUbCHUoHHGYzUmUwkpJ8wJ
```

### getbalance failed!
```
11:44:23.425 ERROR [main] [Client](Client.java:2355) UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
	at org.tron.api.WalletGrpc$WalletBlockingStub.getAccount(WalletGrpc.java:5406)
	at org.tron.walletserver.GrpcClient.queryAccount(GrpcClient.java:106)
	at org.tron.walletserver.WalletApi.queryAccount(WalletApi.java:369)
	at org.tron.walletserver.WalletApi.queryAccount(WalletApi.java:365)
	at org.tron.walletcli.WalletApiWrapper.queryAccount(WalletApiWrapper.java:150)
	at org.tron.walletcli.Client.getBalance(Client.java:234)
	at org.tron.walletcli.Client.run(Client.java:2035)
	at org.tron.walletcli.Client.main(Client.java:2378)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:50051
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	... 11 more
```
### Config.conf

```
net {
 type = mainnet
}

fullnode = {
  ip.list = [
    "127.0.0.1:50051"
  ]
}

soliditynode = {
 ip.list = [
   "127.0.0.1:50052"
  ]
}

RPC_version = 2
```

**Comment by icervot** [comment]
is Tron dead?
I have this issue too. If this is the official wallet-cli, imagine how solid the blockchain must be...

**Comment by zk19862018** [comment]
Use the official public node ip to replace your local ip
https://tronprotocol.github.io/documentation-EN/developers/official-public-nodes/

**Comment by kevinLee2015** [comment]
please try wallet-cli-3.6.5
