### ISSUE TITLE
wallet-cli is crash when i use cmd " GetSpendingKey"  

### ISSUE THREAD

**Issue by ReverseMe** [tronprotocol/wallet-cli#411]
wallet> GetSpendingKey
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.tron.common.zksnark.JLibsodium.<clinit>(JLibsodium.java:13)
        at org.tron.core.zen.address.SpendingKey$PRF.prfExpand(SpendingKey.java:60)
        at org.tron.core.zen.address.SpendingKey$PRF.prfAsk(SpendingKey.java:34)
        at org.tron.core.zen.address.SpendingKey.expandedSpendingKey(SpendingKey.java:20)
        at org.tron.core.zen.address.SpendingKey.fullViewingKey(SpendingKey.java:24)
        at org.tron.walletcli.Client.getSpendingKey(Client.java:2782)
        at org.tron.walletcli.Client.run(Client.java:4063)
        at org.tron.walletcli.Client.main(Client.java:4336)
Caused by: java.lang.RuntimeException: unsupportedPlatformException
        at org.tron.common.util.Utils.getLibrary(Utils.java:25)
        at org.tron.common.util.Utils.getLibraryByName(Utils.java:11)
        at org.tron.common.zksnark.LibsodiumWrapper.<clinit>(LibsodiumWrapper.java:11)
        ... 8 more

**Comment by vivian-kang** [comment]
I test with wallet-cli(4.2.1) and it can execute successfully.
![image](https://user-images.githubusercontent.com/83150421/120440922-9ec35e00-c3b6-11eb-8d3c-3a826bcc3e3e.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to wallet-cli, this issue will be closed since no update for a long time.
Please feel free to re-open it if you still see the issue in the latest version. thanks.
