### ISSUE TITLE
INTERNAL: http2 exception

### ISSUE THREAD

**Issue by safocl** [tronprotocol/wallet-cli#433]
i have archlinux OS, installed open-jdk8.
builded wallet-cli by the readme instructions -- edited config file to:
```
net {
 type = mainnet
}

fullnode = {
  ip.list = [
    "52.53.189.99:8090"
  ]
}

#soliditynode = {
#  // the IPs in this list can only be totally set to solidity or pBFT.
#  ip.list = [
#    "52.53.189.99:8090"
#  ]
#}

RPC_version = 2

# This field used in shielded transaction. It is recommended that this field is set to the b
lock
# number in which the earliest relevant shielded contract was created. If the exact number i
s not
# known, this field can be set as follows. If used in mainnet, please set 22690588. If used
in Nile
# testnet, please set 6380000. Otherwise, please set 0.
blockNumberStartToScan = 22690588
```
i get ip adress from [this git](https://github.com/tronprotocol/documentation/blob/master/TRX/Official_Public_Node.md)
but when i start wallet-cli `/usr/lib/jvm/java-8-openjdk/bin/java -jar ./build/libs/wallet-cli.jar` and do login -- then the getbalance command throw error:
```
GetBalance failed!
INTERNAL: http2 exception
First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```
and the ListNodes command throw error:
```
wallet> ListNodes
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
	at org.tron.api.WalletGrpc$WalletBlockingStub.listNodes(WalletGrpc.java:8050)
	at org.tron.walletserver.GrpcClient.listNodes(GrpcClient.java:583)
	at org.tron.walletserver.WalletApi.listNodes(WalletApi.java:1206)
	at org.tron.walletcli.WalletApiWrapper.listNodes(WalletApiWrapper.java:427)
	at org.tron.walletcli.Client.listNodes(Client.java:1099)
	at org.tron.walletcli.Client.run(Client.java:3994)
	at org.tron.walletcli.Client.main(Client.java:4316)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:448)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
GetAssetIssueList  failed !!!
```

**Comment by safocl** [comment]
as added the login command throw error:
```
wallet> login
user defined config file doesn't exists, use default config file in jar
```

**Comment by liutianv1** [comment]
hello ,can U give some shasta TRX？
my address is TH8b48kpTe4i6pUHfG1w4PwcWdYZRyRMQm

**Comment by Benson0224** [comment]
Wallet-cli is based on GRPC,  from your configuration, you configured HTTP port in that configuration file, which leads to the http2 exceptions.  correct configuration should be : 
` "52.53.189.99:50051"`

**one more note: Please re-compile the jar file after you modify the port, thanks.**

this is the result I connected  52.53.189.99, works perfectly. 


![image](https://user-images.githubusercontent.com/61768920/116344260-8476ed00-a818-11eb-9eea-93c0a208a23e.png)

**Comment by safocl** [comment]
> Wallet-cli is based on GRPC, from your configuration, you configured HTTP port in that configuration file, which leads to the http2 exceptions. correct configuration should be :
> ` "52.53.189.99:50051"`
> 
> **one more note: Please re-compile the jar file after you modify the port, thanks.**
> 
> this is the result I connected 52.53.189.99, works perfectly.

oh, thanks!!! it do work is awesome now
i think might to close this issue now
