### ISSUE TITLE
[Bounty] Cannot fetch account details in wallet-cli

### ISSUE THREAD

**Issue by endeavors** [tronprotocol/wallet-cli#48]
1. What did you do?
I first started java-tron by
./gradlew build
./gradlew -Pwitness
and then started wallet-cli by
./gradlew build
./gradlew -Pcmd

Afterwards, I registered and logged in to a wallet by running 
registerWallet [password] 
login [password]

Then I tried to get the list of accounts and the balance of my wallet by
listaccounts
getblock
getbalance
but I get IO Exception everytime

2. What did you expect to see?
I was expecting to see my balance

3. What did you see instead?

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
        at org.tron.api.WalletSolidityGrpc$WalletSolidityBlockingStub.getAccount(WalletSolidityGrpc.java:920)
        at org.tron.walletserver.GrpcClient.queryAccount(GrpcClient.java:54)
        at org.tron.walletserver.WalletClient.queryAccount(WalletClient.java:225)
        at org.tron.walletserver.WalletClient.queryAccount(WalletClient.java:221)
        at org.tron.walletcli.Client.queryAccount(Client.java:162)
        at org.tron.walletcli.TestClient.getBalance(TestClient.java:156)
        at org.tron.walletcli.TestClient.run(TestClient.java:736)
        at org.tron.walletcli.TestClient.main(TestClient.java:853)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:50050
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
12:20:34.998 [main] INFO TestClient - Get Balance failed !!!!
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused

**Comment by bondibox** [comment]
To expound on this a bit, the listnodes command gives decent output, about 60 nodes connected. I've noticed with this build there are Solidity server settings in the config file, so I opened up port 50050 on the java-tron server, to no avail.

I then installed wallet-web, which works perfectly right out of the box. 😀 
But when I start it with the local web-cli server selected, the webpage gets no data
`API_URL=http://127.0.0.0:8088 yarn start`

**Comment by endeavors** [comment]
Yes, I can confirm listnodes works fine but a lot of the functionalities have become broken after latest commit.

**Comment by grandpaWilly** [comment]
@bondibox I got the same behavior. The documentation says Tronscan.io is the default data source for wallet-cli. However, I also noticed their page is also not showing any data so I suspect the current build has issues. I also noticed this most recent version I pulled was actually able to download blockchain data. 

Still not sure if it was my error or the new build. I opened an issue at the below link with the errors I get trying to poll block data, issuing **Getblock** and receiving the same ** UNAVAILABLE: io exception ** error that was posted above. 

https://github.com/tronprotocol/wallet-cli/issues/50

**Comment by feroult** [comment]
I'm also getting the same error, no 50050 port is opened by the **java-tron** daemon.

Just to check, I even changed the port on **java-tron** config to 50050, and I get this error when I run **GetBalance**

```
 UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetAccount
```

**Comment by jerkyrs** [comment]
The config.conf seems to get updated automatically when you run gradlew run -Pcmd , i tried setting it to port 50051 which is actually listening on the local instance if you are running a witness node but after setting this and looking at it after startup it reverts to port 50050 which has nothing listening.


build/resources/main/config.conf
`fullnode = {
  ip.list = [
    "127.0.0.1:50051"
  ]
}

soliditynode = {
  ip.list = [
    "127.0.0.1:50050"
  ]
}

CityDb = {
  TxtPath = "City.txt"
  DbPath = "GeoLite2-City.mmdb"
}
`

**Comment by bondibox** [comment]
The typical behavior for a gradlew app is to rewrite the config file from source at launch. The original file is in src/main/resources/config.conf

Some say to edit the source file, but since that is part of the git repository, I prefer to copy the config file to the application root. It will check the local search path first and then try build/resources/main/config.conf

If you are running the jar file in build/libs then that is the directory it will check first.

**Comment by endeavors** [comment]
@grandpaWilly How Tronscan.io the default data source of wallet-cli. Doesn't wallet-cli use grpc commands in WalletClient.java

@bondibox It looks we need a fully synced solidity node. Do we have a reliable solidity node available to use with wallet-cli?

**Comment by zergweak** [comment]
@endeavors 
I'm sorry to reply you so late.
RegisterWallet just only generate the private and public key pair and address at local.
You need send more than 1 trx to you address, then it will be create at block chain.

And if you connect to solidity node, you need start solidity service.
Else, you can deleted the config of solidity from wallet-cli

soliditynode = {
  ip.list = [
    "127.0.0.1:50051"
  ]
}

**Comment by axiang-huge** [comment]
The SendCoin command fails to be executed using wallet-cli. What can I do if the following information is displayed?

The failure information is as follows:
sendcoin failed!
ec2a4f2049b9350382906f14a6e70bec4195085f10a812c1c3d8db9c0af154fb701b061fb7bf05c94e4d6a3fc6216f6b27ba88b704853e4396a1bf596ab6bc1d00 is signed by TCaF9bUQzZbBtHXFHcLHKi44g43ijFqdnz but it is not contained of permission.



![Uploading image.png…]()
